# shellcheck disable=all
# --- bootstrap only ---
export ZSH_DIR="$HOME/.zsh"

# autoload 用
fpath=("$ZSH_DIR/functions" $fpath)

# hook は先に読めるようにしておく
autoload -Uz add-zsh-hook

# 各設定ファイルを順に読む
for config in "$ZSH_DIR"/*.zsh(N); do
  source "$config"
done

# functions/ 配下を autoload 対象にする
autoload -Uz "$ZSH_DIR"/functions/*(N:t)

# 必要なら最後に最小限の option だけ
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY
